---

- hosts: all
  become: true
  tasks:

  - name: install apache and jcal packages and update repository
    package:
      name:
         - "{{apache_package }}"
         - "{{jcal_package }}"
      state: latest
      update_cache: yes
