---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    apt:
      name: apache2
      state: absent

  - name: update repository index
    apt:
      update_cache: yes
      

  - name: install jcal package instead of libapache2-mod-php
    apt:
      name: jcal
      state: absent
