---

- hosts: all
  become: true
  tasks:

  - name: install uzip
    package:
      name: unzip


  - name: install terraform on virtual os
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 755
      owner: root
      group: root

    
