- name: install apache2 server package ( Ubuntu and CentOS)
  tags: always
  package:
    name: "{{ apache_package_name }}"
    state: latest


- name: copy file
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
