- name: install uzip
  package:
    name: unzip

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd-config
    owner: root
    group: root
    mode: 0644
    
